version: '3.8'

services:
    website:
        container_name: php-apache
        build:
            context: .
            dockerfile: Dockerfile
        depends_on:
            - db
        ports:
            - 8000:80
    db:
        container_name: db
        image: mysql:8.0.11
        restart: always
        volumes:
            - ./onlineshop.sql:/docker-entrypoint-initdb.d/onlineshop.sql
        environment:
            MYSQL_ROOT_PASSWORD: MYSQL_ROOT_PASSWORD
            MYSQL_DATABASE: onlineshop
            MYSQL_USER: MYSQL_USER
            MYSQL_PASSWORD: MYSQL_PASSWORD
        ports:
            - "9906:3306"
            
    phpmyadmin:
        image: phpmyadmin/phpmyadmin:latest
        ports:
            - '8080:80'
        restart: always
        environment:
            PMA_HOST: db
        depends_on:
            - db